version: '3.9'
services:
  service-discovery:
    container_name: service-discovery
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - 8761:8761
  user-service:
    container_name: user-service
    build:
     context: ./user-service
     dockerfile: Dockerfile
    ports:
      - 9001:9001
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - service-discovery

  order-service:
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - 9002:9002
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - service-discovery

  notification-service:
      container_name: notification-service
      build:
        context: ./notification-service
        dockerfile: Dockerfile
      ports:
        - 9003:9003
      environment:
        - SPRING_PROFILES_ACTIVE=dev
      depends_on:
        - service-discovery

  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - 9004:9004
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - service-discovery

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
